import "./globals.css";
import { Old_Standard_TT } from "next/font/google";
import Header from "./components/Header";
import Sidebar from "./components/Sidebar";
import Footer from "./components/Footer";
import { AuthProvider } from "./components/authContext";
import SmoothScrollProvider from "./components/SmoothScrollProvider";

// Fonts
const oldStandardTT = Old_Standard_TT({
  subsets: ["latin"],
  weight: ["400", "700"],  // Regular + Bold
  display: "swap",
  variable: "--font-old-standard",
});

export const metadata = {
  title: "My Next.js App",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${oldStandardTT.variable}`}
    >
      <body className="font-old-standard">
        {/* ✅ Wrap the app in AuthProvider */}
        <AuthProvider>
          <Header />
          <Sidebar />
          <SmoothScrollProvider>
            <main className="md:mt-22">{children}</main>
          </SmoothScrollProvider>
          <Footer />
        </AuthProvider>
      </body>
    </html>
  );
}